export const SET_NOTES = 'SET_NOTES';
export const SET_API_NOTES = 'SET_API_NOTES';
export const TRIGGER_SAVE_NEW = 'TRIGGER_SAVE_NEW';
export const TRIGGER_DELETE = 'TRIGGER_DELETE';
export const TRIGGER_DELETE_ALL = 'TRIGGER_DELETE_ALL';
export const TRIGGER_MARK_COMPLETE = 'TRIGGER_MARK_COMPLETE';
export const UPDATE_FILTER = 'UPDATE_FILTER';
export const UPDATE_CHECKED_LIST = 'UPDATE_CHECKED_LIST';
